CREATE DATABASE "DSDB"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

-- public."CURRENCY" definition

-- Drop table

-- DROP TABLE "CURRENCY";

CREATE TABLE "CURRENCY" (
  "ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
  "CODE" varchar(3) NOT NULL,
  "SYMBOL" varchar(5) NOT NULL,
  "DESCRIPTION" varchar(256) NOT NULL,
  CONSTRAINT "CURRENCY_pkey" PRIMARY KEY ("ID")
);

INSERT INTO "CURRENCY" ("ID","CODE","SYMBOL","DESCRIPTION") OVERRIDING SYSTEM VALUE VALUES VALUES
   (1,'USD','$','US Dollars'),
   (2,'EUR','€','Euro');

-- public."USER" definition

-- Drop table

-- DROP TABLE "USER";

CREATE TABLE "USER" (
  "ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
  "EMAIL" varchar(125) NOT NULL,
  "USERNAME" varchar(50) NOT NULL,
  "NAME" varchar(50) NOT NULL,
  "SURNAME" varchar(50) NOT NULL,
  CONSTRAINT "USER_pkey" PRIMARY KEY ("ID")
);

INSERT INTO "USER" ("ID","EMAIL","USERNAME","NAME","SURNAME") OVERRIDING SYSTEM VALUE VALUES 
  (1,'pippo@pippo.it','pippo','pippo','pluto');

-- public."ITEM" definition

-- Drop table

-- DROP TABLE "ITEM";

CREATE TABLE "ITEM" (
  "ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
  "NAME" varchar(100) NOT NULL,
  "DESCRIPTION" varchar(256) NOT NULL,
  "STOCK_QTY" int4 NOT NULL DEFAULT 0,
  "START_PRICE" float4 NULL DEFAULT 0,
  "CURRENCY_ID" int4 NOT NULL,
  "AUCTION_HOUR" int4 NOT NULL,
  CONSTRAINT "ITEM_pkey" PRIMARY KEY ("ID")
);

-- public."ITEM" foreign keys

ALTER TABLE public."ITEM" ADD CONSTRAINT "ITEM_CURRENCY" FOREIGN KEY ("CURRENCY_ID") REFERENCES "CURRENCY"("ID");

INSERT INTO "ITEM" ("ID","NAME","DESCRIPTION","STOCK_QTY","START_PRICE","CURRENCY_ID","AUCTION_HOUR") OVERRIDING SYSTEM VALUE VALUES
   (1,'Sedia','La sedia più interessante del mondo',200,50.9,1,5),
   (2,'Tavolo','Il tavolo più bello del mondo',200,50.9,1,5);

-- public."WALLET" definition

-- Drop table

-- DROP TABLE "WALLET";

CREATE TABLE "WALLET" (
  "ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
  "USER_ID" int4 NOT NULL,
  "DISPOSABILITY" float4 NOT NULL DEFAULT 0,
  "CURRENCY_ID" int4 NOT NULL,
  "ACTUAL_STAKED" float4 NULL DEFAULT 0,
  CONSTRAINT "WALLET_pkey" PRIMARY KEY ("ID")
);

-- public."WALLET" foreign keys

ALTER TABLE public."WALLET" ADD CONSTRAINT "WALLET_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID");
ALTER TABLE public."WALLET" ADD CONSTRAINT "WALLET_CURRENCY_ID" FOREIGN KEY ("CURRENCY_ID") REFERENCES "CURRENCY"("ID");

INSERT INTO "WALLET" ("ID","USER_ID","DISPOSABILITY","CURRENCY_ID","ACTUAL_STAKED") OVERRIDING SYSTEM VALUE VALUES
   (2,1,123.213,1,0.0);

-- public."AUCTION" definition

-- Drop table

-- DROP TABLE "AUCTION";

CREATE TABLE "AUCTION" (
  "ID" uuid NOT NULL,
  "ITEM_ID" int4 NULL,
  "UPDATE_TIMESTAMP" timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
  "START_PRICE" float4 NULL,
  "LAST_OFFER" float4 NULL,
  "USER_ID" int4 NULL,
  "END_TIMESTAMP" timestamptz NULL,
  "COMPLETED" bool NOT NULL DEFAULT false,
  "CURRENCY_ID" int4 NOT NULL,
  CONSTRAINT "AUCTION_pkey" PRIMARY KEY ("ID")
);

-- public."AUCTION" foreign keys

ALTER TABLE public."AUCTION" ADD CONSTRAINT "AUCTION_CURRENCY" FOREIGN KEY ("CURRENCY_ID") REFERENCES "CURRENCY"("ID");
ALTER TABLE public."AUCTION" ADD CONSTRAINT "ITEM_ID" FOREIGN KEY ("ITEM_ID") REFERENCES "ITEM"("ID");
ALTER TABLE public."AUCTION" ADD CONSTRAINT "USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID");

-- public."OFFER_HISTORY" definition

-- Drop table

-- DROP TABLE "OFFER_HISTORY";

CREATE TABLE "OFFER_HISTORY" (
  "ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
  "AUCTION_ID" uuid NOT NULL,
  "USER_ID" int4 NOT NULL,
  "TIMESTAMP" timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
  "STAKE" float4 NULL,
  CONSTRAINT "OFFER_HISTORY_pkey" PRIMARY KEY ("ID"),
  CONSTRAINT "UNIQUE_ROW" UNIQUE ("AUCTION_ID", "USER_ID", "STAKE")
);

-- public."OFFER_HISTORY" foreign keys

ALTER TABLE public."OFFER_HISTORY" ADD CONSTRAINT "HISTORY_AUCTION_ID" FOREIGN KEY ("AUCTION_ID") REFERENCES "AUCTION"("ID");
ALTER TABLE public."OFFER_HISTORY" ADD CONSTRAINT "HISTORY_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID");