-- public."ITEM" definition

-- Drop table

-- DROP TABLE "ITEM";

CREATE TABLE "ITEM" (
	"ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	"NAME" varchar(100) NOT NULL,
	"DESCRIPTION" varchar(256) NOT NULL,
	"STOCK_QTY" int4 NOT NULL DEFAULT 0,
	"START_PRICE" float4 NULL DEFAULT 0,
	"CURRENCY_ID" int4 NOT NULL,
	"AUCTION_HOUR" int4 NOT NULL,
	CONSTRAINT "ITEM_pkey" PRIMARY KEY ("ID")
);

-- public."ITEM" foreign keys

ALTER TABLE public."ITEM" ADD CONSTRAINT "ITEM_CURRENCY" FOREIGN KEY ("CURRENCY_ID") REFERENCES "CURRENCY"("ID");

INSERT INTO "ITEM" ("ID","NAME","DESCRIPTION","STOCK_QTY","START_PRICE","CURRENCY_ID","AUCTION_HOUR") OVERRIDING SYSTEM VALUE VALUES
	 (1,'sediapippo','la sedia più interessante del mondo',200,50.9,1,5),
	 (2,'sediapippo','la sedia più interessante del mondo',200,50.9,1,5);