-- public."OFFER_HISTORY" definition

-- Drop table

-- DROP TABLE "OFFER_HISTORY";

CREATE TABLE "OFFER_HISTORY" (
	"ID" int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	"AUCTION_ID" uuid NOT NULL,
	"USER_ID" int4 NOT NULL,
	"TIMESTAMP" timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	"STAKE" float4 NULL,
	CONSTRAINT "OFFER_HISTORY_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "UNIQUE_ROW" UNIQUE ("AUCTION_ID", "USER_ID", "STAKE")
);

-- public."OFFER_HISTORY" foreign keys

ALTER TABLE public."OFFER_HISTORY" ADD CONSTRAINT "HISTORY_AUCTION_ID" FOREIGN KEY ("AUCTION_ID") REFERENCES "AUCTION"("ID");
ALTER TABLE public."OFFER_HISTORY" ADD CONSTRAINT "HISTORY_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID");