apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: zookeeper
spec: 
  selector: 
    matchLabels: 
      app: zookeeper
  replicas: 1
  template:
    metadata: 
      labels: 
        app: zookeeper 
    spec: 
      containers: 
      - name: zookeeper 
        image: library/zookeeper:3.4.13
        env: 
         - name: ZOO_MY_ID
           value: "1"
        ports: 
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: kafka
spec: 
  selector: 
    matchLabels: 
      app: kafka
  replicas: 1
  template:
    metadata: 
      labels: 
        app: kafka 
    spec: 
      containers: 
      - name: kafka 
        image: wurstmeister/kafka:2.11-2.0.0
        env: 
         - name: KAFKA_BROKER_ID
           value: "1" 
         - name: KAFKA_ADVERTISED_HOST_NAME
           value: "kafka"
         - name: KAFKA_ADVERTISED_PORT
           value: "9092"
         - name: BROKER_ID_COMMAND
           value: "hostname | cut -d'-' -f2"
         - name: KAFKA_ZOOKEEPER_CONNECT
           value: "zookeeper:2181"
         - name: KAFKA_CREATE_TOPICS
           value: "auctions" 
         - name: KAFKA_LISTENERS
           value: "PLAINTEXT://kafka:9092"
        ports: 
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kafka      

      