apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: lra-coordinator 
spec: 
  selector: 
    matchLabels: 
      app: lra-coordinator 
  replicas: 1
  template:
    metadata: 
      labels: 
        app: lra-coordinator 
    spec: 
      containers: 
      - name: lra-coordinator 
        image: jbosstm/lra-coordinator:5.9.5.Final
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lra-coordinator-clusteredip
spec:
  selector:
    app: lra-coordinator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080