CREATE DATABASE "AuctionManager"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

CREATE TABLE "USER"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "EMAIL" character varying(125) NOT NULL,
    "USERNAME" character varying(50) NOT NULL,
    "NAME" character varying(50) NOT NULL,
    "SURNAME" character varying(50) NOT NULL,
    PRIMARY KEY ("ID")
);
ALTER TABLE "USER" OWNER to postgres;
    
CREATE TABLE "WALLET"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "USER_ID" integer NOT NULL,
    "DISPOSABILITY" real NOT NULL DEFAULT 0,
    "CURRENCY_ID" integer NOT NULL,
    "ACTUAL_STAKED" real DEFAULT 0,
    PRIMARY KEY ("ID")
);
ALTER TABLE "WALLET"
    ADD CONSTRAINT "WALLET_USER_ID" FOREIGN KEY ("USER_ID")
    REFERENCES "USER" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE "WALLET" OWNER to postgres;

COMMENT ON COLUMN "WALLET"."DISPOSABILITY"
    IS 'Total money on personal wallet';
    
CREATE TABLE "ITEM"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "NAME" character varying(100) NOT NULL,
    "DESCRIPTION" character varying(256) NOT NULL,
    "STOCK_QTY" integer NOT NULL DEFAULT 0,
    "START_PRICE" real DEFAULT 0,
    "CURRENCY_ID" integer NOT NULL,
    "AUCTION_HOUR" integer NOT NULL,
    PRIMARY KEY ("ID")
);
ALTER TABLE "ITEM"
    ADD CONSTRAINT "ITEM_CURRENCY" FOREIGN KEY ("CURRENCY_ID")
    REFERENCES "CURRENCY" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
ALTER TABLE "ITEM" OWNER to postgres;
    
CREATE TABLE "CURRENCY"  ( 
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "SYMBOL"     character varying(5) NOT NULL,
    "DESCRIPTION"  character varying(256) NOT NULL,
    PRIMARY KEY("ID")
);
INSERT INTO "CURRENCY"("CODE", "SYMBOL", "DESCRIPTION")
  VALUES('USD', '$', 'US Dollars');
INSERT INTO "CURRENCY"("CODE", "SYMBOL", "DESCRIPTION")
  VALUES('EUR', '€', 'Euro');
    
CREATE TABLE "AUCTION"
(
    "ID" uuid NOT NULL,
    "ITEM_ID" integer,
    "START_PRICE" real,
    "LAST_OFFER" real,
    "CURRENCY_ID" integer,
    "USER_ID" integer,
    "UPDATE_TIMESTAMP" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "END_TIMESTAMP" timestamp with time zone,
    "COMPLETED" boolean NOT NULL DEFAULT false,
    PRIMARY KEY ("ID"),
    CONSTRAINT "ITEM_ID" FOREIGN KEY ("ITEM_ID")
        REFERENCES "ITEM" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "AUCTION_CURRENCY" FOREIGN KEY ("CURRENCY_ID")
        REFERENCES "CURRENCY" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "USER_ID" FOREIGN KEY ("USER_ID")
        REFERENCES "USER" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE "AUCTION" OWNER to postgres;

CREATE TABLE "OFFER_HISTORY"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "AUCTION_ID" uuid NOT NULL,
    "USER_ID" integer NOT NULL,
    "TIMESTAMP" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "STAKE" real,
    PRIMARY KEY ("ID"),
    CONSTRAINT "HISTORY_USER_ID" FOREIGN KEY ("USER_ID")
        REFERENCES "USER" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "HISTORY_AUCTION_ID" FOREIGN KEY ("AUCTION_ID")
        REFERENCES "AUCTION" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
);

ALTER TABLE "OFFER_HISTORY" OWNER to postgres;
ALTER TABLE "OFFER_HISTORY" ADD CONSTRAINT "UNIQUE_ROW" UNIQUE ("AUCTION_ID", "USER_ID", "STAKE");