apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: zoo1
spec: 
  selector: 
    matchLabels: 
      app: zoo1
  replicas: 1
  template:
    metadata: 
        labels: 
            app: zoo1
    spec: 
      containers: 
      - name: zoo1
        image: zookeeper
        env:        
         - name: ZOO_MY_ID
           value: "1"
         - name: ZOOKEEPER_PORT
           value: "2181"
         - name: ZOOKEEPER_PORT
           value: "server.1=zoo1:2888:3888"
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
spec:
  selector:
    app: zoo1
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: kafka1
spec: 
  selector: 
    matchLabels: 
      app: kafka1
  replicas: 1
  template:
    metadata: 
      labels: 
        app: kafka1
    spec: 
      containers: 
      - name: kafka1
        image: wurstmeister/kafka:2.11-2.0.0
        env: 
         - name: KAFKA_BROKER_ID
           value: "1" 
         - name: KAFKA_ADVERTISED_HOST_NAME
           value: "kafka"
         - name: KAFKA_ADVERTISED_PORT
           value: "9092"
         - name: KAFKA_ADVERTISED_LISTENERS
           value: "INTERNAL://:19092,EXTERNAL://:9092"
         - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
           value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
         - name: KAFKA_INTER_BROKER_LISTENER_NAME
           value: "INTERNAL" 
         - name: KAFKA_LISTENERS
           value: "INTERNAL://:19092,EXTERNAL://:9092"
         - name: KAFKA_ZOOKEEPER_CONNECT
           value: "zoo1:2181"
         - name: KAFKA_LOG4J_LOGGERS
           value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
         - name: KAFKA_CREATE_TOPICS
           value: "auctions:10:1"
        ports: 
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kafka1     

      